<?php

/**
 * @file
 * Optimizes database tables during cron runs.
 *
 * @author David Kent Norman
 *
 * @link http://deekayen.net/
 */

use Drupal\db_maintenance\Module\Db\DbHandler;
use Drupal\db_maintenance\Module\Hook\CommonHookHandler;

/**
 * Implements hook_help().
 */
function db_maintenance_help($path, $arg) {
  return CommonHookHandler::hookHelp($path, $arg);
}

/**
 * Implements hook_permission().
 */
function db_maintenance_permission() {
  return CommonHookHandler::hookPermission();
}

/**
 * Implements hook_menu().
 */
function db_maintenance_menu() {
  $items = CommonHookHandler::hookMenu();
  return $items;
}

/**
 * Implements hook_cron().
 */
function db_maintenance_cron() {
  CommonHookHandler::hookCron();
}

/**
 * Callback page for manually optimizing tables.
 */
function db_maintenance_optimize_tables_page() {
  // db_maintenance_optimize_tables();
  DbHandler::optimizeTables();
  drupal_set_message(t('Database tables optimized'));
  drupal_goto('admin/config/system/db_maintenance');
}
