language: php
before_script:
- composer self-update
- composer install --dev --no-interaction
script:
- vendor/bin/phpunit --coverage-clover clover.xml
after_script:
php:
- 5.4
- 5.5
- 5.6
- 7.0
notifications:
  email: false
